# Generated by Django 3.0.2 on 2020-02-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNumber', models.CharField(default='', max_length=10)),
                ('EmailAddress', models.CharField(default='', max_length=50)),
                ('FirstName', models.CharField(default='', max_length=30)),
                ('LastName', models.CharField(blank=True, default='', max_length=30)),
                ('Adress', models.CharField(blank=True, default='', max_length=50)),
                ('City', models.CharField(blank=True, default='', max_length=20)),
                ('Country', models.CharField(blank=True, default='', max_length=15)),
                ('PostalCode', models.CharField(blank=True, default='', max_length=10)),
                ('AboutMe', models.CharField(blank=True, default='', max_length=50)),
                ('ProfilePic', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
