# Generated by Django 3.0.2 on 2020-02-25 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='PhoneNumber',
            new_name='Username',
        ),
    ]
