# Generated by Django 3.0.2 on 2020-02-25 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_auto_20200225_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Adress',
            new_name='Address',
        ),
    ]
