# Generated by Django 3.0.4 on 2020-07-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0005_remove_userprofile_aboutme'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrides',
            name='isDone',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userrides',
            name='driverId',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
