# Generated by Django 3.0.4 on 2020-07-17 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0006_auto_20200717_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrides',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
