# Generated by Django 3.0.4 on 2020-07-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0007_auto_20200717_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrides',
            name='bargain',
            field=models.TextField(default='[]'),
        ),
    ]
