# Generated by Django 3.0.4 on 2020-07-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0008_userrides_bargain'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrides',
            name='customerAgreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrides',
            name='driverAgreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userrides',
            name='bargain',
            field=models.TextField(default=''),
        ),
    ]
