# Generated by Django 3.0.4 on 2020-07-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0009_auto_20200718_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrides',
            name='stops',
            field=models.TextField(default=''),
        ),
    ]
