# Generated by Django 3.0.2 on 2020-02-22 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetailsinfo',
            name='mobileNumber',
        ),
    ]
