# Generated by Django 3.0.2 on 2020-02-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0003_auto_20200222_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetailsinfo',
            name='isDriver',
            field=models.BooleanField(default=False),
        ),
    ]
