# Generated by Django 3.0.2 on 2020-03-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0004_userdetailsinfo_isdriver'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloseContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('cc1', models.CharField(blank=True, default='', max_length=50)),
                ('cc2', models.CharField(blank=True, default='', max_length=50)),
                ('cc3', models.CharField(blank=True, default='', max_length=50)),
                ('cc4', models.CharField(blank=True, default='', max_length=50)),
                ('cc5', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
    ]
