# Generated by Django 3.0.2 on 2020-03-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0005_closecontacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('sender', models.CharField(default='', max_length=50)),
                ('receiver', models.CharField(default='', max_length=50)),
                ('amount', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WalletMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=100)),
                ('public', models.CharField(default='', max_length=500)),
                ('private', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
