# Generated by Django 3.0.4 on 2020-07-17 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0009_auto_20200717_1151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bargain',
        ),
    ]
